"""Schemas and data models for HomeMind specialized AI agents."""

from __future__ import annotations
from enum import Enum
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field
from datetime import datetime


class AgentType(str, Enum):
    """The 5 primary agent types defined in the HomeMind specification."""
    HOME_MANAGER = "HOME_MANAGER"
    ENERGY = "ENERGY"
    COMFORT = "COMFORT"
    SECURITY = "SECURITY"
    RESOURCE = "RESOURCE"


class AgentStatusEnum(str, Enum):
    """Operational status of an agent."""
    IDLE = "IDLE"
    MONITORING = "MONITORING"
    ANALYZING = "ANALYZING"
    OPTIMIZING = "OPTIMIZING"
    COORDINATING = "COORDINATING"
    ALERTING = "ALERTING"


class ActionPriority(str, Enum):
    """Priority tier for proposed actions."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AgentActionProposal(BaseModel):
    """Structured action proposal suggested by a specialized agent."""
    action_id: str = Field(default_factory=lambda: datetime.utcnow().strftime("%H%M%S%f")[:10])
    agent_type: AgentType
    target_type: str  # "device", "room", "home_state", "inventory"
    target_id: str    # e.g., "ac_bedroom", "light_kitchen"
    action: str       # "TURN_OFF", "TURN_ON", "SET_TEMP", "LOCK", "CHANGE_STATE"
    parameters: Dict[str, Any] = Field(default_factory=dict)
    priority: ActionPriority = ActionPriority.MEDIUM
    reason: str
    explainable_evidence: List[str] = Field(default_factory=list)


class AgentAlert(BaseModel):
    """Explainable alert generated by an agent."""
    alert_id: str = Field(default_factory=lambda: datetime.utcnow().strftime("%H%M%S%f")[:10])
    agent_type: AgentType
    title: str
    severity: str = "INFO"  # "INFO", "WARNING", "CRITICAL"
    description: str
    evidence: List[str] = Field(default_factory=list)  # Observable inputs that triggered alert
    recommended_action: Optional[str] = None


class AgentEvaluationResult(BaseModel):
    """Consolidated assessment generated by an agent in an evaluation cycle."""
    agent_type: AgentType
    agent_name: str
    status: AgentStatusEnum
    current_task: str
    summary: str
    recommendations: List[AgentActionProposal] = Field(default_factory=list)
    alerts: List[AgentAlert] = Field(default_factory=list)
    metrics: Dict[str, Any] = Field(default_factory=dict)


class CoordinatorDecision(BaseModel):
    """Final synthesized multi-agent decision produced by Home Manager Agent."""
    decision_id: str = Field(default_factory=lambda: datetime.utcnow().strftime("%H%M%S%f")[:10])
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    home_state: str
    summary: str
    approved_actions: List[AgentActionProposal] = Field(default_factory=list)
    conflicts_resolved: List[str] = Field(default_factory=list)
    active_alerts: List[AgentAlert] = Field(default_factory=list)
    explanation: str

